const RESET_STATE = 'RESET_STATE';

const SAVE_SORT = 'SAVE_SORT';
const SAVE_SEARCH = 'SAVE_SEARCH';

const SAVE_TAG = 'SAVE_TAG';
const SAVE_TAGS = 'SAVE_TAGS';
const SAVE_ALL_CARDS = 'SAVE_ALL_CARDS';
const SAVE_PLAYING_CARD = 'SAVE_PLAYING_CARD';
const SAVE_RANDOM_PLAYING_CARD = 'SAVE_RANDOM_PLAYING_CARD';

const FILTER_CARDS = 'FILTER_CARDS';

const TOGGLE_PLAY_CARD = 'TOGGLE_PLAY_CARD';
const TOGGLE_SEARCH_MODE = 'TOGGLE_SEARCH_MODE';
const TOGGLE_FAVOURITE_CARD = 'TOGGLE_FAVOURITE_CARD';

export default {
  RESET_STATE,

  SAVE_SORT,
  SAVE_SEARCH,
  SAVE_TAG,
  SAVE_TAGS,
  SAVE_ALL_CARDS,
  SAVE_PLAYING_CARD,
  SAVE_RANDOM_PLAYING_CARD,

  FILTER_CARDS,

  TOGGLE_PLAY_CARD,
  TOGGLE_SEARCH_MODE,
  TOGGLE_FAVOURITE_CARD,
};
