const RESET_STATE = 'RESET_STATE';

const SAVE_SORT = 'SAVE_SORT';
const SAVE_SEARCH = 'SAVE_SEARCH';

const SAVE_TAG = 'SAVE_TAG';
const SAVE_TAGS = 'SAVE_TAGS';
const SAVE_ALL_CARDS = 'SAVE_ALL_CARDS';

const PLAY_CARD = 'PLAY_CARD';
const PLAY_RANDOM_CARD = 'PLAY_RANDOM_CARD';

const FILTER_CARDS = 'FILTER_CARDS';

const TOGGLE_SEARCH_MODE = 'TOGGLE_SEARCH_MODE';
const TOGGLE_FAVOURITE_CARD = 'TOGGLE_FAVOURITE_CARD';

export default {
  RESET_STATE,

  SAVE_SORT,
  SAVE_SEARCH,
  SAVE_TAG,
  SAVE_TAGS,
  SAVE_ALL_CARDS,

  PLAY_CARD,
  PLAY_RANDOM_CARD,

  FILTER_CARDS,

  TOGGLE_SEARCH_MODE,
  TOGGLE_FAVOURITE_CARD,
};
