const SAVE_VOICES = 'SAVE_VOICES';
const FILTER_VOICES = 'FILTER_VOICES';
const SAVE_FAVOURITE_VOICE = 'SAVE_FAVOURITE_VOICE';

export default {
  SAVE_VOICES,
  FILTER_VOICES,
  SAVE_FAVOURITE_VOICE,
};
