const SAVE_TAGS = 'SAVE_TAGS';
const SAVE_VOICES = 'SAVE_VOICES';
const FILTER_VOICES_BY_TAG = 'FILTER_VOICES_BY_TAG';
const FILTER_VOICES_BY_NAME = 'FILTER_VOICES_BY_NAME';
const TOGGLE_SEARCH_MODE = 'TOGGLE_SEARCH_MODE';
const TOGGLE_FAVOURITE_VOICE = 'TOGGLE_FAVOURITE_VOICE';

export default {
  SAVE_TAGS,
  SAVE_VOICES,
  FILTER_VOICES_BY_TAG,
  FILTER_VOICES_BY_NAME,
  TOGGLE_SEARCH_MODE,
  TOGGLE_FAVOURITE_VOICE,
};
